language: python

python:
    - "3.6"

env:
    - SECRET_KEY="TEST1"

services:
    - mysql

install:
    - pipenv install

script:
    - pipenv run python manage.py runserver
    - pipenv run pip list

