language: python

python:
    - "3.6"

env:
    - SECRET_KEY="TEST1"
    - DJANGO_VERSION=3.1.1 DB=mysql

services:
    - mysql

install:
    - pipenv install
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install

script:
    - pipenv run pip list
    - pipenv run python -m django --version
